### ISSUE TITLE
XML Parsing error in gpxpy parser

### ISSUE THREAD

**Issue by ivangayton** [localdevices/ODMax#44]
# Apparent XML parsing issue
## Context and error message
Clean install of ODMax using the developer install instructions (Conda, ```pip install -e .```). Given [this video file](https://drive.google.com/file/d/1jWjMxhGG8BED2d-z7lZRNHh_c0q3cRQk/view?usp=sharing), I get this output including the error:

```
(odmax) ivan@ivan-hc:~/Documents/git/ODMax$ odmax -r -f 1024 -m bilinear -s 0 -e 1 -d 5 -i '/home/ivan/Documents/Maps/Nakuru_Kenya/go pro max trial videos-20220801T085436Z-001/go pro max trial videos/GS010034.360' -o '/home/ivan/Documents/Maps/Nakuru_Kenya/go pro max trial videos-20220801T085436Z-001/go pro max trial videos/GS010034_MAXXED.360' 
Processing video  : /home/ivan/Documents/Maps/Nakuru_Kenya/go pro max trial videos-20220801T085436Z-001/go pro max trial videos/GS010034.360
Output path       : /home/ivan/Documents/Maps/Nakuru_Kenya/go pro max trial videos-20220801T085436Z-001/go pro max trial videos/GS010034_MAXXED.360
Encoder           : jpg
File prefix       : still
Start time        : 0.0 seconds
End time          : 1.0 seconds
Frame interval    : 5
Reprojection      : enabled
Reprojection mode : bilinear
Face width        : 1024
Output path /home/ivan/Documents/Maps/Nakuru_Kenya/go pro max trial videos-20220801T085436Z-001/go pro max trial videos/GS010034_MAXXED.360 does not exist, creating path...
exiftool          : found! Processing with GPS coordinates if available
====================
Start processing:
====================
Collecting metadata:
--------------------
Traceback (most recent call last):
  File "/home/ivan/anaconda3/envs/odmax/lib/python3.8/site-packages/gpxpy/parser.py", line 134, in parse
    root = mod_etree.XML(self.xml)
  File "/home/ivan/anaconda3/envs/odmax/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ivan/anaconda3/envs/odmax/bin/odmax", line 8, in <module>
    sys.exit(main())
  File "/home/ivan/anaconda3/envs/odmax/lib/python3.8/site-packages/odmax/cli.py", line 58, in main
    Video = odmax.Video(options.infile)
  File "/home/ivan/anaconda3/envs/odmax/lib/python3.8/site-packages/odmax/api.py", line 31, in __init__
    self.gpx = odmax.io.get_gpx(self.fn)
  File "/home/ivan/anaconda3/envs/odmax/lib/python3.8/site-packages/odmax/io.py", line 137, in get_gpx
    return gpxpy.parse(helpers.exiftool('-ee', '-p', f"{gpx_fmt_fn}", fn))
  File "/home/ivan/anaconda3/envs/odmax/lib/python3.8/site-packages/gpxpy/__init__.py", line 39, in parse
    return parser.parse(version)
  File "/home/ivan/anaconda3/envs/odmax/lib/python3.8/site-packages/gpxpy/parser.py", line 146, in parse
    raise mod_gpx.GPXXMLSyntaxException('Error parsing XML: %s' % str(e), e)
gpxpy.gpx.GPXXMLSyntaxException: Error parsing XML: not well-formed (invalid token): line 1, column 0

```

It appears that the ```gpxpy``` library is not happy with the GPX XML it's getting.

## Contents of apparently offending XML
Using exiftool standalone I should be able to create the same XML content like so: ```exiftool -ee -p /path/to/gpx.fmt path/to/GS010034.360```. As far as I can see this is how the exiftool call is constructed in ```io.py``` and sent to ```helpers.py```. Running it standalone on the same file, I obtain the following GPX XML (truncated):

```
<?xml version="1.0" encoding="utf-8"?>
<gpx version="1.0"
 creator="ExifTool 11.88"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns="http://www.topografix.com/GPX/1/0"
 xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd">
<trk>
<number>1</number>
<trkseg>
<trkpt lat="-0.2853" lon="36.0694">
</trkpt>
<trkpt lat="-0.2853306" lon="36.069363">
  <ele>1847.689</ele>
  <time>2022-07-31T15:03:28.989Z</time>
...
</trkseg>
</trk>
</gpx>
```
Parsing that directly in Python with gpxpy doesn't result in any error, and the resulting object produces sensible output from its ```get_points_data()``` method. Therefore most likely the XML being fetched by exiftool within the code is not the same as the XML I generated with exiftool manually.

Hypothesis: the bloody ```gpx.fmt``` file path isn't correct in the exiftool call; that could cause the problem by returning either nothing or garbage. It would also make sense that it works on @hcwinsemius's machine (where the specific path to ```gpx.fmt``` happens to be valid) but not on mine.

It seems that the ```gpx.fmt``` pathname is constructed in ```io.py``` on line 11, ```PATH = os.path.dirname(__file__)```. That doesn't work in an interpreter, so I can't tell whether it's going wrong; it should be ok because the ```gpx.fmt``` file is in the same directory as ```io.py```.

**Comment by ivangayton** [comment]
I can test this by inserting a print statement or debug point in ```io.py```, but at the moment I assume this requires me to step out of the Conda environment, remove it, re-create it, and reinstall odmax after adding the relevant checkpoint. I'm not immediately sure if there's a faster way to try little changes.

**Comment by ivangayton** [comment]
Ok, I added a print statement to check on the path description of ```gpx.fmt```, torched the Conda environment and re-installed everything, and **_incredibly bizarrely_** the result was:

it gave the correct path *and then the processing worked.* I mean, what the heck??!!?

**Comment by ivangayton** [comment]
Right, so it fixed itself. For now closing this issue, though it may become relevant again in the future!
